version: '3'
services:
  sls-path-optimiser:
    build: ./sls-path-optimiser
    ports:
      - "3050:3000"
    links:
      - db
    environment:
      - DB=mongodb://db:27017/db
      - PORT=3050
      - API_CONFEDERATION=http://confederation:3020
    networks:
      - tpsuperheroes

  sls-villain:
    build: ./sls-villain
    ports:
    - "3060:3000"
    links:
    - db
    environment:
    - DB=mongodb://db:27017/db
    - PORT=3060
    - API_CONFEDERATION=http://confederation:3020
    - SLS_CITY=http://sls-city:3000
    networks:
    - tpsuperheroes

  sls-hero:
    build: ./sls-hero
    ports:
    - "3070:3000"
    links:
    - db
    environment:
    - DB=mongodb://db:27017/db
    - PORT=3070
    - API_CONFEDERATION=http://confederation:3020
    - SLS_CITY=http://sls-city:3000
    - SLS_VILLAIN=http://sls-villain:3000
    networks:
    - tpsuperheroes

  sls-mount:
    build: ./sls-mount
    ports:
      - "3080:3000"
    links:
      - db
    environment:
      - DB=mongodb://db:27017/db
      - PORT=3080
      - API_CONFEDERATION=http://confederation:3020
    networks:
      - tpsuperheroes

  sls-city:
    build: ./sls-city
    ports:
    - "3090:3000"
    links:
    - db
    environment:
    - DB=mongodb://db:27017/db
    - PORT=3060
    - API_CONFEDERATION=http://confederation:3020
    networks:
    - tpsuperheroes

  ember-map:
    build: ./ember-map
    ports:
      - "3100:3000"
    links:
      - db
    environment:
      - DB=mongodb://db:27017/db
      - PORT=3100
      - API_CONFEDERATION=http://confederation:3020
    networks:
      - tpsuperheroes

  confederation:
    build: ./confederation
    ports:
    - "3020:3020"
    environment:
    - PORT=3020
    - SLS_VILLAIN=http://sls-villain:3000
    - SLS_HERO=http://sls-hero:3000
    - SLS_CITY=http://sls-city:3000
    - SLS_OPTI=http://sls-path-optimiser:3000
    networks:
    - tpsuperheroes

  db:
    image: mongo
    ports:
    - "27027:27017"
    networks:
      - tpsuperheroes

networks:
  tpsuperheroes:
