service: sls-path-optimiser

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    iterationMax: 100
    iterationMin: 10
    maxDistance: 5

functions:
  optimisePath:
    handler: src/optimizer.optimizePath
    events:
      - http: POST /optimisePath

plugins:
- serverless-offline