service: sls-hero

provider:
  name: aws
  runtime: nodejs8.10

functions:
  newHero:
    handler: src/new-hero.addHeroHandler
    events:
      - http: POST /newHero

  getHeroes:
    handler: src/get-heroes.getHeroesAvailableHandler
    events:
      - http: GET /getHeroes

  intallHero:
    handler: src/install-hero.installHeroHandler
    events:
      - http: POST /installHero

  addToDoList:
    handler: src/add-to-do-list.addTicketHandler
    events:
      - http: POST /addTicket

  getToDoList:
    handler: src/get-to-do-list.getTicketsHandler
    events:
      - http: POST /getTickets

  hookHero:
    handler: src/hook-hero.hookHeroHandler
    events:
      - http: POST /hookHero

plugins:
- serverless-offline