service: sls-hero

provider:
  name: aws
  runtime: nodejs8.10

functions:
  newHero:
    handler: src/new-hero.addHeroHandler
    events:
      - http: POST /newHero

  getHeroes:
    handler: src/get-heroes.getHeroesAvailableHandler
    events:
      - http: GET /getHeroes

  intallHero:
    handler: src/install-hero.installHeroHandler
    events:
      - http: POST /installHero

plugins:
- serverless-offline