service: sls-city

provider:
  name: aws
  runtime: nodejs8.10

functions:
  newCity:
    handler: src/new-city.addCityHandler
    events:
      - http: POST /newCity

  getCities:
    handler: src/get-cities.getCitiesHandler
    events:
      - http: GET /getCities

  installCities:
    handler: src/install-cities.installCitiesHandler
    events:
    - http: POST /installCities

plugins:
- serverless-offline